export {
  getSupabaseClient,
  getSupabaseConfig,
  resetSupabaseClient,
  PAYMENT_PROOFS_BUCKET
} from "./lib/supabaseClient";

export {
  submitPublicGiving,
  fetchFinanceSnapshot,
  updateFinanceRecordStatus,
  updateFinanceGroupStatus,
  uploadPaymentProof,
  signInWithEmail,
  isSupabaseConfigured
} from "./lib/financeRepository";

export { mapFinanceRecordToDashboard, mapSubmissionToDashboard } from "./lib/mappers";

// Progressive data layer (mock / local / api / supabase)
export {
  getDataProvider,
  resetDataProvider,
  getActiveDataSource,
  getDataSource,
  getApiBaseUrl,
  listDataSources,
  createMockProvider,
  createLocalStorageProvider,
  createApiProvider,
  createSupabaseProvider,
  // Churches
  listChurches,
  getChurchById,
  createChurch,
  updateChurch,
  deleteChurch,
  searchChurches,
  getChurchServiceTimes,
  ensureChurchesSeeded,
  getChurchesDataSourceInfo,
  CHURCHES_SEED,
  // Members
  listMembers,
  getMemberById,
  createMember,
  updateMember,
  deleteMember,
  searchMembers,
  getMembersByChurch,
  getMembersByCell,
  getMembersByCellGroup,
  getMembersByDepartment,
  getActiveMembers,
  getInactiveMembers,
  ensureMembersSeeded,
  getMembersDataSourceInfo,
  normalizeMember,
  MEMBERS_SEED,
  // First Timers
  listFirstTimers,
  getFirstTimerById,
  createFirstTimer,
  updateFirstTimer,
  deleteFirstTimer,
  searchFirstTimers,
  getFirstTimersByChurch,
  getFirstTimersByCell,
  getFirstTimersByCellGroup,
  getFirstTimersByStatus,
  getFirstTimersByDateRange,
  getNewConverts,
  getPendingFirstTimersFollowUps,
  getInterestedInFoundationSchool,
  convertFirstTimerToMember,
  ensureFirstTimersSeeded,
  getFirstTimersDataSourceInfo,
  normalizeFirstTimer,
  FIRST_TIMERS_SEED,
  // Follow-Ups / Acompanhamento
  listFollowUps,
  getFollowUpById,
  createFollowUp,
  updateFollowUp,
  deleteFollowUp,
  searchFollowUps,
  getFollowUpsByChurch,
  getFollowUpsByCell,
  getFollowUpsByCellGroup,
  getFollowUpsByStatus,
  getFollowUpsByResponsibleUser,
  getFollowUpsByDateRange,
  getPendingFollowUps,
  getOverdueFollowUps,
  getTodayFollowUps,
  getFollowUpsByFirstTimer,
  createFollowUpFromFirstTimer,
  markFollowUpBecameMember,
  ensureFollowUpsSeeded,
  getFollowUpsDataSourceInfo,
  normalizeFollowUp,
  FOLLOW_UPS_SEED,
  // Foundation School
  listFoundationStudents,
  getFoundationStudentById,
  createFoundationStudent,
  updateFoundationStudent,
  deleteFoundationStudent,
  searchFoundationStudents,
  getFoundationStudentsByChurch,
  getFoundationStudentsByClassGroup,
  getFoundationStudentsByStatus,
  getFoundationStudentsByQuarter,
  getReadyForExamStudents,
  getReadyForGraduationStudents,
  getGraduatedStudents,
  listFoundationClasses,
  getFoundationClassById,
  createFoundationClass,
  updateFoundationClass,
  deleteFoundationClass,
  getFoundationClassesByChurch,
  getActiveFoundationClasses,
  listFoundationTeachers,
  getFoundationTeacherById,
  createFoundationTeacher,
  updateFoundationTeacher,
  deleteFoundationTeacher,
  getActiveFoundationTeachers,
  getFoundationTeachersByChurch,
  ensureFoundationSchoolSeeded,
  getFoundationSchoolDataSourceInfo,
  normalizeFoundationStudent,
  normalizeFoundationTeacher,
  normalizeFoundationClass,
  listStudents,
  createStudent,
  updateStudent,
  deleteStudent,
  listClasses,
  createClass,
  updateClass,
  listTeachers,
  createTeacher,
  updateTeacher,
  FOUNDATION_STUDENTS_SEED,
  FOUNDATION_TEACHERS_SEED,
  FOUNDATION_CLASSES_SEED,
  // Cell Ministry
  listCellGroups,
  getCellGroupById,
  createCellGroup,
  updateCellGroup,
  deleteCellGroup,
  searchCellGroups,
  getCellGroupsByChurch,
  getActiveCellGroups,
  getCellGroupsNeedingReview,
  listCells,
  getCellById,
  createCell,
  updateCell,
  deleteCell,
  searchCells,
  getCellsByGroup,
  getCellsByChurch,
  getActiveCells,
  getCellsNeedingReview,
  getCellsWithoutReport,
  listCellLeaders,
  getCellLeaderById,
  createCellLeader,
  updateCellLeader,
  deleteCellLeader,
  getLeadersByCell,
  getLeadersByGroup,
  getLeadersByChurch,
  listCellReports,
  getCellReportById,
  createCellReport,
  updateCellReport,
  deleteCellReport,
  getCellReportsByWeek,
  getCellReportsByCell,
  getCellReportsByGroup,
  getCellReportsByChurch,
  getPendingCellReports,
  getValidatedCellReports,
  getReportsNeedingReview,
  getCellReportsWithOffering,
  getDuplicateReports,
  ensureCellMinistrySeeded,
  getCellMinistryDataSourceInfo,
  normalizeCellGroup,
  normalizeCell,
  normalizeCellLeader,
  normalizeCellReport,
  CELL_GROUPS_SEED,
  CELLS_SEED,
  CELL_LEADERS_SEED,
  CELL_REPORTS_SEED,
} from "./data";

export type {
  DataProvider,
  DataSourceName,
  DataResult,
  EntityRepository,
  ListOptions,
  User,
  Church,
  Member,
  FirstTimer,
  FollowUp,
  FollowUpTimelineEvent,
  FoundationStudent,
  FoundationTeacher,
  FoundationClassGroup,
  FoundationLessonSession,
  FoundationTestSubmission,
  FoundationFinalExam,
  FinanceRecord,
  Requisition,
  Notification,
  CellGroup,
  Cell,
  CellLeader,
  CellReportSubmission,
  MediaTechnician,
  MediaSchedule,
  EntityCollectionName
} from "./data";

import {
  listChurches,
  getChurchById,
  createChurch,
  updateChurch,
  deleteChurch,
  searchChurches,
  getChurchServiceTimes,
  ensureChurchesSeeded,
  getChurchesDataSourceInfo,
  listMembers,
  getMemberById,
  createMember,
  updateMember,
  deleteMember,
  searchMembers,
  getMembersByChurch,
  getMembersByCell,
  getMembersByCellGroup,
  getMembersByDepartment,
  getActiveMembers,
  getInactiveMembers,
  ensureMembersSeeded,
  getMembersDataSourceInfo,
  listFirstTimers,
  getFirstTimerById,
  createFirstTimer,
  updateFirstTimer,
  deleteFirstTimer,
  searchFirstTimers,
  getFirstTimersByChurch,
  getFirstTimersByCell,
  getFirstTimersByCellGroup,
  getFirstTimersByStatus,
  getFirstTimersByDateRange,
  getNewConverts,
  getPendingFirstTimersFollowUps,
  getInterestedInFoundationSchool,
  convertFirstTimerToMember,
  ensureFirstTimersSeeded,
  getFirstTimersDataSourceInfo,
  listFollowUps,
  getFollowUpById,
  createFollowUp,
  updateFollowUp,
  deleteFollowUp,
  searchFollowUps,
  getFollowUpsByChurch,
  getFollowUpsByCell,
  getFollowUpsByCellGroup,
  getFollowUpsByStatus,
  getFollowUpsByResponsibleUser,
  getFollowUpsByDateRange,
  getPendingFollowUps,
  getOverdueFollowUps,
  getTodayFollowUps,
  getFollowUpsByFirstTimer,
  createFollowUpFromFirstTimer,
  markFollowUpBecameMember,
  ensureFollowUpsSeeded,
  getFollowUpsDataSourceInfo,
  listFoundationStudents,
  getFoundationStudentById,
  createFoundationStudent,
  updateFoundationStudent,
  deleteFoundationStudent,
  searchFoundationStudents,
  getFoundationStudentsByChurch,
  getFoundationStudentsByClassGroup,
  getFoundationStudentsByStatus,
  getFoundationStudentsByQuarter,
  getReadyForExamStudents,
  getReadyForGraduationStudents,
  getGraduatedStudents,
  listFoundationClasses,
  getFoundationClassById,
  createFoundationClass,
  updateFoundationClass,
  deleteFoundationClass,
  getFoundationClassesByChurch,
  getActiveFoundationClasses,
  listFoundationTeachers,
  getFoundationTeacherById,
  createFoundationTeacher,
  updateFoundationTeacher,
  deleteFoundationTeacher,
  getActiveFoundationTeachers,
  getFoundationTeachersByChurch,
  ensureFoundationSchoolSeeded,
  getFoundationSchoolDataSourceInfo,
  listStudents,
  createStudent,
  updateStudent,
  deleteStudent,
  listClasses,
  createClass,
  updateClass,
  listTeachers,
  createTeacher,
  updateTeacher,
  listCellGroups,
  getCellGroupById,
  createCellGroup,
  updateCellGroup,
  deleteCellGroup,
  searchCellGroups,
  getCellGroupsByChurch,
  getActiveCellGroups,
  getCellGroupsNeedingReview,
  listCells,
  getCellById,
  createCell,
  updateCell,
  deleteCell,
  searchCells,
  getCellsByGroup,
  getCellsByChurch,
  getActiveCells,
  getCellsNeedingReview,
  getCellsWithoutReport,
  listCellLeaders,
  getCellLeaderById,
  createCellLeader,
  updateCellLeader,
  deleteCellLeader,
  getLeadersByCell,
  getLeadersByGroup,
  getLeadersByChurch,
  listCellReports,
  getCellReportById,
  createCellReport,
  updateCellReport,
  deleteCellReport,
  getCellReportsByWeek,
  getCellReportsByCell,
  getCellReportsByGroup,
  getCellReportsByChurch,
  getPendingCellReports,
  getValidatedCellReports,
  getReportsNeedingReview,
  getCellReportsWithOffering,
  getDuplicateReports,
  ensureCellMinistrySeeded,
  getCellMinistryDataSourceInfo,
  CELL_GROUPS_SEED,
  CELLS_SEED,
  CELL_LEADERS_SEED,
  CELL_REPORTS_SEED,
  getDataProvider,
  getDataSource,
  getActiveDataSource,
  resetDataProvider,
  listDataSources,
  getApiBaseUrl,
} from "./data";

function installDataLayerGlobals(): void {
  const root = globalThis as typeof globalThis & {
    CESupabase?: Record<string, unknown>;
    CEDataLayer?: Record<string, unknown>;
    CEChurches?: Record<string, unknown>;
    CEMembers?: Record<string, unknown>;
    CEFirstTimers?: Record<string, unknown>;
    CEFollowUps?: Record<string, unknown>;
    CEFoundationSchool?: Record<string, unknown>;
    CECellMinistry?: Record<string, unknown>;
  };

  const churches = {
    listChurches,
    getChurchById,
    createChurch,
    updateChurch,
    deleteChurch,
    searchChurches,
    getChurchServiceTimes,
    ensureChurchesSeeded,
    getChurchesDataSourceInfo,
  };

  const members = {
    listMembers,
    getMemberById,
    createMember,
    updateMember,
    deleteMember,
    searchMembers,
    getMembersByChurch,
    getMembersByCell,
    getMembersByCellGroup,
    getMembersByDepartment,
    getActiveMembers,
    getInactiveMembers,
    ensureMembersSeeded,
    getMembersDataSourceInfo,
  };

  const firstTimers = {
    listFirstTimers,
    getFirstTimerById,
    createFirstTimer,
    updateFirstTimer,
    deleteFirstTimer,
    searchFirstTimers,
    getFirstTimersByChurch,
    getFirstTimersByCell,
    getFirstTimersByCellGroup,
    getFirstTimersByStatus,
    getFirstTimersByDateRange,
    getNewConverts,
    getPendingFollowUps: getPendingFirstTimersFollowUps,
    getInterestedInFoundationSchool,
    convertFirstTimerToMember,
    ensureFirstTimersSeeded,
    getFirstTimersDataSourceInfo,
  };

  const followUps = {
    listFollowUps,
    getFollowUpById,
    createFollowUp,
    updateFollowUp,
    deleteFollowUp,
    searchFollowUps,
    getFollowUpsByChurch,
    getFollowUpsByCell,
    getFollowUpsByCellGroup,
    getFollowUpsByStatus,
    getFollowUpsByResponsibleUser,
    getFollowUpsByDateRange,
    getPendingFollowUps,
    getOverdueFollowUps,
    getTodayFollowUps,
    getFollowUpsByFirstTimer,
    createFollowUpFromFirstTimer,
    markFollowUpBecameMember,
    ensureFollowUpsSeeded,
    getFollowUpsDataSourceInfo,
  };

  const foundationSchool = {
    listStudents: listFoundationStudents,
    createStudent: createFoundationStudent,
    updateStudent: updateFoundationStudent,
    deleteStudent: deleteFoundationStudent,
    listFoundationStudents,
    getFoundationStudentById,
    createFoundationStudent,
    updateFoundationStudent,
    deleteFoundationStudent,
    searchFoundationStudents,
    getFoundationStudentsByChurch,
    getFoundationStudentsByClassGroup,
    getFoundationStudentsByStatus,
    getFoundationStudentsByQuarter,
    getReadyForExamStudents,
    getReadyForGraduationStudents,
    getGraduatedStudents,
    listClasses: listFoundationClasses,
    createClass: createFoundationClass,
    updateClass: updateFoundationClass,
    listFoundationClasses,
    getFoundationClassById,
    createFoundationClass,
    updateFoundationClass,
    deleteFoundationClass,
    getFoundationClassesByChurch,
    getActiveFoundationClasses,
    listTeachers: listFoundationTeachers,
    createTeacher: createFoundationTeacher,
    updateTeacher: updateFoundationTeacher,
    listFoundationTeachers,
    getFoundationTeacherById,
    createFoundationTeacher,
    updateFoundationTeacher,
    deleteFoundationTeacher,
    getActiveFoundationTeachers,
    getFoundationTeachersByChurch,
    ensureFoundationSchoolSeeded,
    getFoundationSchoolDataSourceInfo,
    getInfo: getFoundationSchoolDataSourceInfo,
  };

  const cellMinistry = {
    listCellGroups,
    getCellGroupById,
    createCellGroup,
    updateCellGroup,
    deleteCellGroup,
    searchCellGroups,
    getCellGroupsByChurch,
    getActiveCellGroups,
    getCellGroupsNeedingReview,
    listCells,
    getCellById,
    createCell,
    updateCell,
    deleteCell,
    searchCells,
    getCellsByGroup,
    getCellsByChurch,
    getActiveCells,
    getCellsNeedingReview,
    getCellsWithoutReport,
    listCellLeaders,
    getCellLeaderById,
    createCellLeader,
    updateCellLeader,
    deleteCellLeader,
    getLeadersByCell,
    getLeadersByGroup,
    getLeadersByChurch,
    listCellReports,
    getCellReportById,
    createCellReport,
    updateCellReport,
    deleteCellReport,
    getCellReportsByWeek,
    getCellReportsByCell,
    getCellReportsByGroup,
    getCellReportsByChurch,
    getPendingCellReports,
    getValidatedCellReports,
    getReportsNeedingReview,
    getCellReportsWithOffering,
    getDuplicateReports,
    ensureCellMinistrySeeded,
    getCellMinistryDataSourceInfo,
    getInfo: getCellMinistryDataSourceInfo,
  };

  const cellGroups = {
    listCellGroups,
    getCellGroupById,
    createCellGroup,
    updateCellGroup,
    deleteCellGroup,
    searchCellGroups,
    getCellGroupsByChurch,
    getActiveCellGroups,
    getCellGroupsNeedingReview,
  };

  const cells = {
    listCells,
    getCellById,
    createCell,
    updateCell,
    deleteCell,
    searchCells,
    getCellsByGroup,
    getCellsByChurch,
    getActiveCells,
    getCellsNeedingReview,
    getCellsWithoutReport,
  };

  const cellReports = {
    listCellReports,
    getCellReportById,
    createCellReport,
    updateCellReport,
    deleteCellReport,
    getCellReportsByWeek,
    getCellReportsByCell,
    getCellReportsByGroup,
    getCellReportsByChurch,
    getPendingCellReports,
    getValidatedCellReports,
    getReportsNeedingReview,
    getCellReportsWithOffering,
    getDuplicateReports,
  };

  root.CESupabase = Object.assign(root.CESupabase || {}, {
    ...churches,
    ...members,
    ...firstTimers,
    ...followUps,
    ...foundationSchool,
    ...cellMinistry,
    CELL_GROUPS_SEED,
    CELLS_SEED,
    CELL_LEADERS_SEED,
    CELL_REPORTS_SEED,
    getDataProvider,
    getDataSource,
    getActiveDataSource,
    resetDataProvider,
    listDataSources,
    getApiBaseUrl,
  });

  root.CEDataLayer = {
    churches,
    members,
    firstTimers,
    followUps,
    foundationSchool,
    cellMinistry,
    cellGroups,
    cells,
    cellReports,
    getDataProvider,
    getDataSource,
    getActiveDataSource,
    resetDataProvider,
    listDataSources,
    get dataSource() {
      return getDataSource();
    },
  };

  if (!root.CEChurches) {
    root.CEChurches = { ...churches, getInfo: getChurchesDataSourceInfo };
  }
  if (!root.CEMembers) {
    root.CEMembers = { ...members, getInfo: getMembersDataSourceInfo };
  }
  if (!root.CEFirstTimers) {
    root.CEFirstTimers = { ...firstTimers, getInfo: getFirstTimersDataSourceInfo };
  }
  if (!root.CEFollowUps) {
    root.CEFollowUps = { ...followUps, getInfo: getFollowUpsDataSourceInfo };
  }
  if (!root.CEFoundationSchool) {
    root.CEFoundationSchool = foundationSchool;
  }
  if (!root.CECellMinistry) {
    root.CECellMinistry = cellMinistry;
  }

  try {
    const churchInfo = getChurchesDataSourceInfo();
    console.info("[CE DataLayer] globals installed", {
      source: churchInfo.source,
      provider: churchInfo.provider,
      ready: churchInfo.ready,
      churches: Object.keys(churches),
      members: Object.keys(members),
      firstTimers: Object.keys(firstTimers),
      followUps: Object.keys(followUps),
      foundationSchool: Object.keys(foundationSchool),
      cellMinistry: Object.keys(cellMinistry),
    });
  } catch (error) {
    console.warn("[CE DataLayer] installed with provider warning", error);
  }
}

installDataLayerGlobals();
